### ISSUE TITLE
Gulp pipeline upgrade

### ISSUE THREAD

**Issue by marksweb** [django-cms/djangocms-admin-style#444]
I've started to upgrade the gulp pipeline based on the upgrade made to django-cms itself which is now using node 16.

https://github.com/marksweb/djangocms-admin-style/tree/feat/node-upgrade

However here, there's a problem with webpack during bundling.

```
% gulp bundle
[00:10:59] Using gulpfile ~/apps/djangocms-admin-style/gulpfile.js
[00:10:59] Starting 'bundle'...
[00:10:59] 'bundle' errored after 17 ms
[00:10:59] TypeError: webpack.optimize.OccurenceOrderPlugin is not a constructor
    at module.exports (/Users/mwalker/apps/djangocms-admin-style/webpack.config.js:54:13)
    at /Users/mwalker/apps/djangocms-admin-style/gulpfile.js:134:51
    at taskWrapper (/Users/mwalker/apps/djangocms-admin-style/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (/Users/mwalker/apps/djangocms-admin-style/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

I'm not familiar with webpack, and not had a lot of time, so currently not progressed with this.

**Comment by marksweb** [comment]
Fixed by #445 I think
